version: '2'
services:
  fpm:
    image: dvaquero/alpine-php:7-dev
    container_name: app_dev_fpm
    ports:
      - "2222:22"
      - "9000:9000"
    volumes:
      - "$PWD:/app"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tic_tac_toe
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
